// <auto-generated />
namespace MVCGarage25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fnatteinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fnatteinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201610260932430_Fnatte init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
